version: "2"
services:
    web:
      build: .
      ports:
        - "3000:80"
      volumes: 
        - ./:/var/www/
        - /var/www/node_modules
        - /var/www/vendor
      network_mode: bridge
    mysql:
      image: mysql
      ports:
        - 3313:3306
      environment:
        MYSQL_DATABASE: carts
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - /var/lib/mysql
      network_mode: bridge
    testdb:
      image: mysql
      environment:
        MYSQL_DATABASE: testdb
        MYSQL_ROOT_PASSWORD: root
      network_mode: bridge